"""add private key password hash field

Revision ID: 58a476dd4368
Revises: bfebf8975081
Create Date: 2025-08-03 16:48:37.727616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58a476dd4368'
down_revision: Union[str, Sequence[str], None] = 'bfebf8975081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('private_key_password_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'private_key_password_hash')
    # ### end Alembic commands ###
