"""Add public_key to User model

Revision ID: cdb3ddf9aeac
Revises: f3f15d106be6
Create Date: 2025-07-27 11:27:33.744853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdb3ddf9aeac'
down_revision: Union[str, Sequence[str], None] = 'f3f15d106be6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('conversation_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'conversation_id')
    # ### end Alembic commands ###
