"""refactor message service and dependency injection

Revision ID: e47898757f87
Revises: cdb3ddf9aeac
Create Date: 2025-07-27 12:54:10.369086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e47898757f87'
down_revision: Union[str, Sequence[str], None] = 'cdb3ddf9aeac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_read_receipts')
    op.drop_table('deleted_conversations')
    op.drop_table('deleted_messages')
    op.add_column('messages', sa.Column('is_read', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('is_deleted_for_all', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('encrypted_private_key', sa.String(), nullable=True))
    op.add_column('users', sa.Column('salt', sa.String(), nullable=True))
    op.add_column('users', sa.Column('iv', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'iv')
    op.drop_column('users', 'salt')
    op.drop_column('users', 'encrypted_private_key')
    op.drop_column('messages', 'is_deleted_for_all')
    op.drop_column('messages', 'is_read')
    op.create_table('deleted_messages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('deleted_messages_message_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('deleted_messages_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('deleted_messages_pkey'))
    )
    op.create_table('deleted_conversations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('deleted_conversations_conversation_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('deleted_conversations_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('deleted_conversations_pkey'))
    )
    op.create_table('message_read_receipts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('read_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('message_read_receipts_message_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('message_read_receipts_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('message_read_receipts_pkey'))
    )
    # ### end Alembic commands ###
